In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])

In [4]:
arr[0]

1

In [5]:
arr[1]

2

In [6]:
arr[1:4]

array([2, 3, 4])

In [7]:
arr[ : -1]

array([1, 2, 3, 4, 5])

In [8]:
arr[ : ]

array([1, 2, 3, 4, 5, 6])

In [9]:
arr2=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [12]:
arr2[0,1]

2

In [13]:
arr2[2,0]

7

In [15]:
arr2[ :1, : ]

array([[1, 2, 3]])

In [16]:
arr2[: 3, :3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])