In [1]:
import numpy as np

In [7]:
arr=np.array([[9,3,2],
              [1,6,5],
              [2,8,7]])

In [8]:
np.sort(arr,axis=0,kind="mergesort")
# axis=0 means sort columnWise

array([[1, 3, 2],
       [2, 6, 5],
       [9, 8, 7]])

In [10]:
np.sort(arr,axis=1,kind="mergesort")
# axis=1 means sort rowWise

array([[2, 3, 9],
       [1, 5, 6],
       [2, 7, 8]])

In [11]:
np.sort(arr,kind="mergesort")
# if axis is not provided, it'll automatically sort it rowWise

array([[2, 3, 9],
       [1, 5, 6],
       [2, 7, 8]])