In [1]:
import numpy as np

In [3]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[9,8,7,6],[5,4,3,2]])

In [4]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2

array([[9, 8, 7, 6],
       [5, 4, 3, 2]])

In [7]:
# 2 functions for merging
# vstack() ....vertical stack ....for merging row wise
# hstack() ....horizontal stack ....for merging row wise

np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [8]:
np.vstack((arr2,arr1))

array([[9, 8, 7, 6],
       [5, 4, 3, 2],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [5, 6, 7, 8, 5, 4, 3, 2]])

In [10]:
np.hstack((arr2,arr1))

array([[9, 8, 7, 6, 1, 2, 3, 4],
       [5, 4, 3, 2, 5, 6, 7, 8]])

In [11]:
np.concatenate((arr1,arr2),axis=1)
# axis=0 means vertical stack

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [5, 6, 7, 8, 5, 4, 3, 2]])

In [12]:
np.concatenate((arr1,arr2),axis=1)
# axis=1 means horizontal stack

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [5, 6, 7, 8, 5, 4, 3, 2]])

In [13]:
# split is the reverse process of stack
# hsplit()....hstack()
# vsplit()....vstack()

np.hsplit(arr1,2)  # slpit into 2 parts

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [15]:
np.vsplit(arr1,2)  # slpit into 2 parts

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]