In [3]:
import numpy as np

In [4]:
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2=np.array([[1,1,1],
               [3,3,3],
               [5,5,5]])
# for all operations, shape of the bith arrays should be same

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5]])

In [7]:
arr1+arr2

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [8]:
arr1-arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [9]:
arr1*arr2

array([[ 1,  2,  3],
       [12, 15, 18],
       [35, 40, 45]])

In [10]:
arr2*arr1

array([[ 1,  2,  3],
       [12, 15, 18],
       [35, 40, 45]])

In [11]:
arr1.dot(arr2)

array([[22, 22, 22],
       [49, 49, 49],
       [76, 76, 76]])

In [12]:
arr2.dot(arr1)

array([[12, 15, 18],
       [36, 45, 54],
       [60, 75, 90]])

In [13]:
arr3=np.array([1,2,3,4,5])

In [14]:
arr3[0]

1

In [16]:
arr3[0:3]

array([1, 2, 3])

In [19]:
arr3[2:-1]

array([3, 4])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr1[ : , : ]
# [rows,col]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr1[ :1, : ]

array([[1, 2, 3]])

In [23]:
arr1[ : , :1 ]

array([[1],
       [4],
       [7]])

In [24]:
arr1[ :1, : 1]

array([[1]])

In [26]:
 arr1[ : , 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
arr1[1:2,1:2]
# middle element

array([[5]])