In [2]:
import numpy as np

In [3]:
arr=np.random.random((3,4))
arr

array([[0.92721571, 0.41832601, 0.21918693, 0.91962469],
       [0.72603535, 0.219213  , 0.14030626, 0.6276404 ],
       [0.50036672, 0.35527108, 0.85101833, 0.85555078]])

In [5]:
arr2=np.arange(1,20,2)
print(arr2)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [ ]:
# size of the initial and final array should be same
arr=np.reshape(arr,(4,3))
arr

array([[0.71649642, 0.61402936, 0.95798518],
       [0.09451758, 0.78921061, 0.45289638],
       [0.51545824, 0.85710198, 0.20847322],
       [0.02805014, 0.73445298, 0.23000226]])

In [ ]:
arr.flatten()
# converts any 'n' dimensional array to 1-D

array([0.71649642, 0.61402936, 0.95798518, 0.09451758, 0.78921061,
       0.45289638, 0.51545824, 0.85710198, 0.20847322, 0.02805014,
       0.73445298, 0.23000226])