In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [9]:
print(arr+1) # adds 1 to every element of array
print(arr-2)
print(arr*2)
print(arr/2)
print(arr**2)

[2 3 4 5 6]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


In [10]:
arr=arr+1

In [11]:
arr+=2

In [12]:
arr

array([4, 5, 6, 7, 8])

In [13]:
arr*=2
arr

array([ 8, 10, 12, 14, 16])

In [14]:
arr.max() # returns the maximum element of the element

16

In [15]:
arr.min() # minimum element of the array

8

In [16]:
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
 arr.max(axis=0) # max element by column wise

array([3, 6, 9])

In [19]:
 arr.max(axis=1) # max element row wise

In [21]:
 arr.min(axis=0) # min element by column wise

array([1, 2, 3])

In [22]:
arr.min(axis=1) # min element by row wise

array([1, 4, 7])